// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: ipam.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllocateIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"` // CNI 请求的容器 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateIPRequest) Reset() {
	*x = AllocateIPRequest{}
	mi := &file_ipam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateIPRequest) ProtoMessage() {}

func (x *AllocateIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateIPRequest.ProtoReflect.Descriptor instead.
func (*AllocateIPRequest) Descriptor() ([]byte, []int) {
	return file_ipam_proto_rawDescGZIP(), []int{0}
}

func (x *AllocateIPRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type AllocateIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"` // 分配的 IP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateIPResponse) Reset() {
	*x = AllocateIPResponse{}
	mi := &file_ipam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateIPResponse) ProtoMessage() {}

func (x *AllocateIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateIPResponse.ProtoReflect.Descriptor instead.
func (*AllocateIPResponse) Descriptor() ([]byte, []int) {
	return file_ipam_proto_rawDescGZIP(), []int{1}
}

func (x *AllocateIPResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type ReleaseIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseIPRequest) Reset() {
	*x = ReleaseIPRequest{}
	mi := &file_ipam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseIPRequest) ProtoMessage() {}

func (x *ReleaseIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseIPRequest.ProtoReflect.Descriptor instead.
func (*ReleaseIPRequest) Descriptor() ([]byte, []int) {
	return file_ipam_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseIPRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type ReleaseIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseIPResponse) Reset() {
	*x = ReleaseIPResponse{}
	mi := &file_ipam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseIPResponse) ProtoMessage() {}

func (x *ReleaseIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseIPResponse.ProtoReflect.Descriptor instead.
func (*ReleaseIPResponse) Descriptor() ([]byte, []int) {
	return file_ipam_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseIPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseIPResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ipam_proto protoreflect.FileDescriptor

const file_ipam_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"ipam.proto\x12\x04ipam\"6\n" +
	"\x11AllocateIPRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"$\n" +
	"\x12AllocateIPResponse\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"5\n" +
	"\x10ReleaseIPRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"G\n" +
	"\x11ReleaseIPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x85\x01\n" +
	"\x04IPAM\x12?\n" +
	"\n" +
	"AllocateIP\x12\x17.ipam.AllocateIPRequest\x1a\x18.ipam.AllocateIPResponse\x12<\n" +
	"\tReleaseIP\x12\x16.ipam.ReleaseIPRequest\x1a\x17.ipam.ReleaseIPResponseB\x04Z\x02./b\x06proto3"

var (
	file_ipam_proto_rawDescOnce sync.Once
	file_ipam_proto_rawDescData []byte
)

func file_ipam_proto_rawDescGZIP() []byte {
	file_ipam_proto_rawDescOnce.Do(func() {
		file_ipam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ipam_proto_rawDesc), len(file_ipam_proto_rawDesc)))
	})
	return file_ipam_proto_rawDescData
}

var file_ipam_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ipam_proto_goTypes = []any{
	(*AllocateIPRequest)(nil),  // 0: ipam.AllocateIPRequest
	(*AllocateIPResponse)(nil), // 1: ipam.AllocateIPResponse
	(*ReleaseIPRequest)(nil),   // 2: ipam.ReleaseIPRequest
	(*ReleaseIPResponse)(nil),  // 3: ipam.ReleaseIPResponse
}
var file_ipam_proto_depIdxs = []int32{
	0, // 0: ipam.IPAM.AllocateIP:input_type -> ipam.AllocateIPRequest
	2, // 1: ipam.IPAM.ReleaseIP:input_type -> ipam.ReleaseIPRequest
	1, // 2: ipam.IPAM.AllocateIP:output_type -> ipam.AllocateIPResponse
	3, // 3: ipam.IPAM.ReleaseIP:output_type -> ipam.ReleaseIPResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ipam_proto_init() }
func file_ipam_proto_init() {
	if File_ipam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ipam_proto_rawDesc), len(file_ipam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ipam_proto_goTypes,
		DependencyIndexes: file_ipam_proto_depIdxs,
		MessageInfos:      file_ipam_proto_msgTypes,
	}.Build()
	File_ipam_proto = out.File
	file_ipam_proto_goTypes = nil
	file_ipam_proto_depIdxs = nil
}
