// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: ipam.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IPAM_AllocateIP_FullMethodName = "/ipam.IPAM/AllocateIP"
	IPAM_ReleaseIP_FullMethodName  = "/ipam.IPAM/ReleaseIP"
)

// IPAMClient is the client API for IPAM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IPAMClient interface {
	// 分配 IP
	AllocateIP(ctx context.Context, in *AllocateIPRequest, opts ...grpc.CallOption) (*AllocateIPResponse, error)
	// 释放 IP
	ReleaseIP(ctx context.Context, in *ReleaseIPRequest, opts ...grpc.CallOption) (*ReleaseIPResponse, error)
}

type iPAMClient struct {
	cc grpc.ClientConnInterface
}

func NewIPAMClient(cc grpc.ClientConnInterface) IPAMClient {
	return &iPAMClient{cc}
}

func (c *iPAMClient) AllocateIP(ctx context.Context, in *AllocateIPRequest, opts ...grpc.CallOption) (*AllocateIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateIPResponse)
	err := c.cc.Invoke(ctx, IPAM_AllocateIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPAMClient) ReleaseIP(ctx context.Context, in *ReleaseIPRequest, opts ...grpc.CallOption) (*ReleaseIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseIPResponse)
	err := c.cc.Invoke(ctx, IPAM_ReleaseIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IPAMServer is the server API for IPAM service.
// All implementations must embed UnimplementedIPAMServer
// for forward compatibility.
type IPAMServer interface {
	// 分配 IP
	AllocateIP(context.Context, *AllocateIPRequest) (*AllocateIPResponse, error)
	// 释放 IP
	ReleaseIP(context.Context, *ReleaseIPRequest) (*ReleaseIPResponse, error)
	mustEmbedUnimplementedIPAMServer()
}

// UnimplementedIPAMServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIPAMServer struct{}

func (UnimplementedIPAMServer) AllocateIP(context.Context, *AllocateIPRequest) (*AllocateIPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocateIP not implemented")
}
func (UnimplementedIPAMServer) ReleaseIP(context.Context, *ReleaseIPRequest) (*ReleaseIPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseIP not implemented")
}
func (UnimplementedIPAMServer) mustEmbedUnimplementedIPAMServer() {}
func (UnimplementedIPAMServer) testEmbeddedByValue()              {}

// UnsafeIPAMServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IPAMServer will
// result in compilation errors.
type UnsafeIPAMServer interface {
	mustEmbedUnimplementedIPAMServer()
}

func RegisterIPAMServer(s grpc.ServiceRegistrar, srv IPAMServer) {
	// If the following call pancis, it indicates UnimplementedIPAMServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IPAM_ServiceDesc, srv)
}

func _IPAM_AllocateIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPAMServer).AllocateIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPAM_AllocateIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPAMServer).AllocateIP(ctx, req.(*AllocateIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPAM_ReleaseIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPAMServer).ReleaseIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPAM_ReleaseIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPAMServer).ReleaseIP(ctx, req.(*ReleaseIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IPAM_ServiceDesc is the grpc.ServiceDesc for IPAM service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IPAM_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ipam.IPAM",
	HandlerType: (*IPAMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocateIP",
			Handler:    _IPAM_AllocateIP_Handler,
		},
		{
			MethodName: "ReleaseIP",
			Handler:    _IPAM_ReleaseIP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ipam.proto",
}
